### ISSUE TITLE
Scope and filtering

### ISSUE THREAD

**Issue by franzejr** [codevise/activeadmin-searchable_select#1]
Hello! Nice library!

I would like to know if using scope can also be a filter. Suppose In my scope, I will use `Post.limi(5)`, for example. This would make the only 5 posts be loaded?

**Comment by tf** [comment]
Hi,

you are free to use all of ActiveRecord's query methods to restrict the scope passed to `searchable_select_options`. `limit` and `offset` will be overridden by [the built in pagination](https://github.com/codevise/activeadmin-searchable_select/blob/647bf3689451b20fbd60cbc8829d5459319ff12b/lib/activeadmin/searchable_select/option_collection.rb#L63), though. You can restrict the number of initially loaded posts to 5 by passing the `per_page` option:

```ruby
searchable_select_options(scope: Post.all,
                          text_attribute: :title,
                          per_page: 5)
```

Scrolling to the end of the drop down list will load the next 5 items, though. If you really only want to offer the first five posts, I suppose, you would have to construct your scope via some `where` condition.
