### ISSUE TITLE
Support for conditional collection

### ISSUE THREAD

**Issue by vicenteferreyra** [codevise/activeadmin-searchable_select#20]
Hi there! 

Is there any way of populating the select using the value of another input and refresh it when the other input changes?
e.g:

```
f.input(:user)
f.input(:posts,
        as: :searchable_select,
        collection: <user_selected_in_input>.posts
})
```

I would appreciate any help on this!

**Comment by tf** [comment]
This is not supported currently and will need additional custom JavaScript code to incorporate the current value of the other input in the options requests. You will probably be able to reuse option endpoints defined via `searchable_select_options`, though. There is support for [passing custom parameters](https://github.com/codevise/activeadmin-searchable_select#passing-parameters) to options endpoints, but those need to be known when rendering the form. Select2 appears to support [dynamically assembling the options URL](https://select2.org/data-sources/ajax#dynamic-urls) (I did not check whether the these docs actually talk about the same Select2 version used by this gem). I imagine, additional custom logic will be needed to reset dependent selects when inputs change etc.

**Comment by vicenteferreyra** [comment]
Hey, thanks for your response. I actually do this by writting custom js but since I have been doing it so many times, I thought it could be a good feature.

**Comment by tf** [comment]
I agree. Happy to accept a PR. Just not sure what a minimal feature set could look like here.
