### ISSUE TITLE
Add ruby 3.0.0 support

### ISSUE THREAD

**Issue by durcak** [codevise/activeadmin-searchable_select#24]
**What language does this apply to?**
ruby

**Describe the problem you are trying to solve.**
Ruby 3.0.0 was released, which is not supported:

`activeadmin-searchable_select-1.2.1 requires ruby version ~> 2.1, which is incompatible with the current version, ruby 3.0.0p0`

**Describe the solution you'd like**
The activeadmin-searchable_select gem is installable under ruby 3.0.0.

**Comment by tf** [comment]
Opened a PR, but we still need to fine update the Appraisal setup to use Rails and Active Admin versions that are compatible with Ruby 3. Which versions are you using in the app where you want to use this gem?

**Comment by durcak** [comment]
Rails 6.1.0 and activeadmin 2.9.0, thanks.

**Comment by tf** [comment]
Added Rails 6.x to the CI matrix. Appears to [fail](https://github.com/codevise/activeadmin-searchable_select/pull/26/checks?check_run_id=1680501011) because of a [Ruby 3 compat issue in Formtastic](https://github.com/activeadmin/activeadmin/issues/6671). Are you seeing that issue in your app as well?

**Comment by durcak** [comment]
Yes!

**Comment by tf** [comment]
Ok, then we will probably have to wait until AcriveAdmin/Formastic are Ruby 3 compatible before we can move forward here.

**Comment by durcak** [comment]
Formtastic 4.0.0 has been released and its Ruby 3.0 compatible, can we move forward here?

**Comment by tf** [comment]
Good to hear. #26 passed now. Merged and released as 1.3.
