### ISSUE TITLE
Not support resource class that placed in module

### ISSUE THREAD

**Issue by Ivanov-Anton** [codevise/activeadmin-searchable_select#29]
For example we have class Main::User
I want to perform search my users via ajax but I got error: 

`Cannot auto detect resource to fetch options for searchable select input from`

**Comment by tf** [comment]
A possible solution should be suggested as part of the [error message](https://github.com/codevise/activeadmin-searchable_select/blob/1eb2ccd3457d1e641e489aa4e232eeded3da987e/lib/activeadmin/searchable_select/select_input_extension.rb#L109), i.e. [explicitly specifying the options endpoint resource](https://github.com/codevise/activeadmin-searchable_select#specifying-the-options-endpoint-resource). Or is this is this a different problem?

**Comment by Ivanov-Anton** [comment]
Main::Order have relation named :invoice, class_name: 'Main::Invoice' this is belongs_to type so
In ActiveAdmn page of order I define `filter :invoice, as: :searchable_select, ajax: true`
in ActiveAdmin page of Invoice I define `searchable_select_options scope: Main::Invoice.all, text_attribute: :name`

Finaly I expect to render Order page and searchable select is work

but I got error: `undefined method `all_options_admin_main_invoices_path' for #<#<Class:0x00007fce8737f4a8>:0x00007fce8737cfc8>`

**Comment by Ivanov-Anton** [comment]
I have all_options_admin_invoices_path route instead

**Comment by Ivanov-Anton** [comment]
If I set config named resource got another error:
`filter :invoice, as: :searchable_select, ajax: { resource: 'Main::Invoice' }`

`undefined method all_options_admin_Main::Invoice_path' for #<#<Class:0x00007f8ce4375eb0>:0x00007f8ce4360498>`

**Comment by Ivanov-Anton** [comment]
So looks like this gem do not support Namespaced Classes

**Comment by tf** [comment]
Try passing the resource without quotes: `filter :invoice, as: :searchable_select, ajax: { resource: Main::Invoice }`

**Comment by tf** [comment]
How does the `ActiveAdmin.register` call for invoices look like?

**Comment by Ivanov-Anton** [comment]
> How does the `ActiveAdmin.register` call for invoices look like?

ActiveAdmin.register Main::Invoice, as: 'Invoice' do

**Comment by Ivanov-Anton** [comment]
> Try passing the resource without quotes: `filter :invoice, as: :searchable_select, ajax: { resource: Main::Invoice }`

`filter :invoice, as: :searchable_select, ajax: { resource: Main::Invoice }`

result error: `undefined method all_options_admin_main_invoices_path' for #<#<Class:0x00007fa21b0aeac8>:0x00007fa21b09ead8>
Did you mean?  all_options_admin_invoices_path`

**Comment by tf** [comment]
That's exactly the same setup I use in one of our engines. There it works without a problem. Not sure what the difference is. Maybe you can spot it?

https://github.com/codevise/pageflow/blob/fedf751ba8abb79d593d76f328db60359350c560/admins/pageflow/entry.rb#L60-L63

https://github.com/codevise/pageflow/blob/fedf751ba8abb79d593d76f328db60359350c560/admins/pageflow/accounts.rb#L43-L48

**Comment by Ivanov-Anton** [comment]
The difference is that the model class does not lie inside the namespace

**Comment by Ivanov-Anton** [comment]
In your case belongs_to :account, counter_cache: true
in my case belongs_to :invoice, class_name: 'Main::Invoice', foreign_key: :invoice_id

**Comment by tf** [comment]
It does. `Pageflow::Entry`/`Pageflow::Account`. The whole file is wrapped in `module Pageflow`. What might be the difference is that `Pageflow` is an engine. `Main` is only a module I guess.

Can you try `filter :invoice, as: :searchable_select, ajax: { resource: 'invoice' }`.

**Comment by tf** [comment]
Sorry. I meant: `filter :invoice, as: :searchable_select, ajax: { resource: 'invoices' }.`. Plural.

**Comment by Ivanov-Anton** [comment]
> Sorry. I meant: `filter :invoice, as: :searchable_select, ajax: { resource: 'invoices' }`. Plural.

undefined method `name' for "invoices":String excluded from capture: No host specified, no public_key specified, no project_id specified

**Comment by tf** [comment]
Yeah, I thought it might get passed through to the [`polymorphic_path` call](https://github.com/codevise/activeadmin-searchable_select/blob/1eb2ccd3457d1e641e489aa4e232eeded3da987e/lib/activeadmin/searchable_select/select_input_extension.rb#L48) that generated the URL, but it is also used to look up the admin resource and is thus expected to be a class.

So the problem appears to be that we currently cannot handle the case where the model is namespaced by a module but the admin is not namespaced (`as: 'Invoice'`). In my engine case it appears to work since the engine namespace is removed (e.g. `polymorphic_path('admin', Pageflow::Entry) #=> /admin/entries`).

Happy to accept a PR that also makes it work in this case. It might be worth investigating whether we can also read the path from the admin resource instead of constructing it ourselves (using something like `template.active_admin_namespace.resource_for(ajax_resource_class).route_collection_path`)

**Comment by Ivanov-Anton** [comment]
Thanks!

**Comment by tf** [comment]
Fixed in #30.
