### ISSUE TITLE
Undefined method 'all_options_admin_users_path'

### ISSUE THREAD

**Issue by davidwparker** [codevise/activeadmin-searchable_select#3]
Having issues getting this to work.

Note: we have 3x different namespaces for different Active Admin interfaces. (Admin2, Super, Custom).

admin2/flag.rb
```
  form do |f|
    f.semantic_errors
    f.inputs do
      f.input :assigned_user, as: :searchable_select, ajax: { resource: User }
      f.input :admin_notes
    end
    f.actions
  end
```

admin2/user.rb
```
searchable_select_options(scope: User.all, text_attribute: :username)
```

When that's setup like that, I get the following error:

```
undefined method `all_options_admin_users_path' for #<#<Class:0x00007fc178072b50>:0x00007fc178062b88>
Did you mean?  all_options_admin2_users_path
               all_options_admin2_users_url
```

Suggestions? Thanks!

**Comment by davidwparker** [comment]
Follow up:

Note that when I change this line:
https://github.com/codevise/activeadmin-searchable_select/blob/c9373a9239e0cf6cb44c5f11bfd47d076f164b19/lib/activeadmin/searchable_select/select_input_extension.rb#L48

`template.polymorphic_path([:admin, ajax_resource_class],`
to
`template.polymorphic_path([:admin2, ajax_resource_class],`

it renders, but now I get the console error:
```
Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
```

So it would be nice to have this library pass in which namespace it is within.

**Comment by tf** [comment]
Hi,

a PR making the namespace configurable is definitely welcome. I'd suggest passing it in as part of the `ajax` option:

```
f.input(:additional_category,
        as: :searchable_select,
        ajax: {
          namespace: :admin2, 
          resource: Category 
        })
```

As an extra, one could look into using the name of the current namespace as a default. This should work the same way [we currently determine the default resource](https://github.com/codevise/activeadmin-searchable_select/blob/c9373a9239e0cf6cb44c5f11bfd47d076f164b19/lib/activeadmin/searchable_select/select_input_extension.rb#L95).

Regarding the second error: What version of `select2-rails` are you using?

**Comment by davidwparker** [comment]
Cool, I'll take a look into making a PR!

In regards to the latter, it's whatever was autoinstalled with this gem, so (https://github.com/codevise/activeadmin-searchable_select/blob/master/activeadmin-searchable_select.gemspec#L34)? I'll take a look when I get more time to switch back to this branch.

**Comment by tf** [comment]
Great!

I can only find the mentioned error message in [the source code of the 3.5 verion](https://github.com/argerim/select2-rails/blob/3-5-stable/vendor/assets/javascripts/select2.js#L934), though. [In 4.0](https://github.com/argerim/select2-rails/blob/v4.0.0/vendor/assets/javascripts/select2.js) I no longer find it. Could you check your `Gemfile.lock` or even the Select2 version comment in the js file inside the browser, to see which version you are using.

**Comment by davidwparker** [comment]
Here's what I'm seeing via the Gemfile

```
    activeadmin-searchable_select (1.0.1)
      activeadmin (~> 1.x)
      jquery-rails (>= 3.0, < 5)
      select2-rails (~> 4.0)
    select2-rails (4.0.3)
      thor (~> 0.14)
```

But when I look at the JS source, I see this:
```
Version: 3.5.1 Timestamp: Tue Jul 22 18:58:56 EDT 2014
```

It appears our app was using an older version of `select2` that was overriding `select2-rails`. I'll be checking with my team to see if we can upgrade...

**Comment by davidwparker** [comment]
Also, removing the old one does allow for things to work, albeit the CSS is a little off.

<img width="275" alt="screen shot 2018-02-06 at 4 26 27 pm" src="https://user-images.githubusercontent.com/2379/35889885-9026c296-0b5a-11e8-8b47-b7c55901e00e.png">
<img width="188" alt="screen shot 2018-02-06 at 4 26 47 pm" src="https://user-images.githubusercontent.com/2379/35889886-903e882c-0b5a-11e8-8110-7ea904856b15.png">

Forward progress!

**Comment by tf** [comment]
Importing [`active_admin/searchable_select.scss`](https://github.com/codevise/activeadmin-searchable_select/blob/master/app/assets/stylesheets/active_admin/searchable_select.scss#L1) should include the required styles.

**Comment by davidwparker** [comment]
Again, we had the old version of 3.5 select2 SCSS. Removing that fixed the CSS problem!

Thanks again! I'll see about that PR still.

**Comment by davidwparker** [comment]
Oh, one more thing to suggest. It would be nice to be able to query against multiple `text_attributes` in a single select2. 

For example:
```
searchable_select_options(
    scope: User.all,
    text_attribute: [:email, :username]
  )
```
Would search against `email` and `username` (using `OR`).

I don't know Ransack very well (I should research more!), but I figure this is the place I should be looking?
https://github.com/codevise/activeadmin-searchable_select/blob/master/lib/activeadmin/searchable_select/option_collection.rb#L90

**Comment by tf** [comment]
Looking at [this Ransack wiki page](https://github.com/activerecord-hackery/ransack/wiki/basic-searching), something like the following should do the trick:
```ruby
searchable_select_options(scope: User.all,
                          text_attribute: :username,
                          filter: lambda |term, scope|
                            scope.ransack(email_or_username_cont: term).result
                          end)
```

**Comment by davidwparker** [comment]
Works perfectly thanks! When I get a PR up, I'll be sure to throw something like that in the documentation too, as it's helpful to know.

**Comment by davidwparker** [comment]
Here you go, thanks for the help! https://github.com/codevise/activeadmin-searchable_select/pull/4
