### ISSUE TITLE
not have ability to add additional payload of the ajax response

### ISSUE THREAD

**Issue by Ivanov-Anton** [codevise/activeadmin-searchable_select#32]
At the moment ajax response contains the folowwing payload: text and id
We have ability to config text attributes but we don't have ability to add new payload.
It would be nice to have something like this:

```
searchable_select_options scope: Post, text_attributes: :tite, additional_payload: ->(record) { { custom_field: record.custom_field, created_at: record.created_at } }
```

-------------------------------
I suggest that you do this because someone can only use your gem to build the JSON endpoint to provides the options

**Comment by tf** [comment]
Fixed by #33.
