### ISSUE TITLE
Searchable select with webpacker

### ISSUE THREAD

**Issue by dmitrybereza** [codevise/activeadmin-searchable_select#35]
Hi, I have a question, how I can add activeadmin_searchable_select with webpacker?

**Comment by tf** [comment]
Hi, currently not supported. Looking at other gems (e.g., Active Admin), it looks like using Rollup to build a UMD file in `app/assets/javascripts` and also publishing that as a npm package appears to be the norm. I'd be happy to support this setup, but currently do not have the time to work on it myself.

If you just need a quick workaround, you could probably copy the content of the [main JS file](https://github.com/codevise/activeadmin-searchable_select/blob/ac15d4f7eb0442f6f542d110153f43b5b24a2575/app/assets/javascripts/active_admin/searchable_select/init.js) to your app and add imports for jQuery and Select2.

**Comment by dmitrybereza** [comment]
Hi, t u for your help, discussed with the team, and think that we can migrate to sprockets)

**Comment by tf** [comment]
npm package for use with Webpacker is now available as well: https://www.npmjs.com/package/@codevise/activeadmin-searchable_select. Thanks @Skumring!
