### ISSUE TITLE
Set default values while loading the page

### ISSUE THREAD

**Issue by anson2590** [codevise/activeadmin-searchable_select#36]
Hi, while loading the page by default I need some values to be selected in the searchable select field, and is it possible to dynamically load data to drop down. Can you please guide me on how to achieve it?

**Comment by tf** [comment]
Sorry for being super late to respond. Setting defaults should work exactly the same as for normal select inputs. You will need to set the value on the model object used in the form. 

Feel free to open another issue with a more specific question regarding loading data to help us improve the README.
