### ISSUE TITLE
Multiple Select not showing all initially selected options

### ISSUE THREAD

**Issue by bkubic** [codevise/activeadmin-searchable_select#6]
I have a multiple select box that works as expected to select and save multiple options. However, when I reload the form, only the first selected option shows up in the select2 box, even though all the previously selected relationships are saved in the database.

This only happens when using AJAX - when I provide a collection instead the box works as expected.

```
ActiveAdmin.register Offer do
  form do |f|
    f.input :buyers, as: :searchable_select, ajax: true, multiple: true
  end
end
```

```
ActiveAdmin.register Buyer do
  searchable_select_options(scope: Buyer.all.order(last_name: :asc),
                             text_attribute: :name_email,
                             filter: lambda{|term, scope| scope.ransack(first_name_or_last_name_or_email_cont: term.downcase, phone_number_cont: (term.gsub(/\D/, '').presence || "XXX"), m: 'or' ).result})
end
```

**Comment by tf** [comment]
There is currently no support for select inputs with multiple options. The initially rendered select box [only contains a single option](https://github.com/codevise/activeadmin-searchable_select/blob/master/lib/activeadmin/searchable_select/select_input_extension.rb#L60) corresponding to the current attribute value. That way the current selection can already be displayed correctly while all other options are only loaded once the select is interacted with.

This logic would probably need to be extended to render all selected options for the multiple case. Happy to accept a PR.
