### ISSUE TITLE
Test against AA 2.0.0.alpha?

### ISSUE THREAD

**Issue by davidwparker** [codevise/activeadmin-searchable_select#9]
Is there a way we can test gem against AA 2.0.0.alpha?

**Comment by tf** [comment]
We could test against additional combinations of Rails and AA versions using the exiting [Appraisals setup](https://github.com/codevise/activeadmin-searchable_select/blob/master/Appraisals) and include that in the [Travis build](https://github.com/codevise/activeadmin-searchable_select/blob/d53b2460d4ec470f7d2b6f93cd5922b4518a33cc/.travis.yml#L12). Using a `git` source, it should also be possible to test agains AA master.

Happy to accept PRs.

Is AA 2.0 about to happen anytime soon? Could not find unreleased breaking changes in the changelog.

**Comment by davidwparker** [comment]
I'm not sure when AA 2.0 will be happening. I'm not sure why they went with 2.0 if there's no breaking changes either.

I'll submit a PR using Appraisals (didn't know about that, thanks!)

**Comment by tobsch** [comment]
@davidwparker 2.0.0 is out. seems to be uncritical in total.

**Comment by tf** [comment]
Thanks for the heads up. Added support for 2.0 in #13 and [released as 1.2](https://github.com/codevise/activeadmin-searchable_select/blob/1-2-stable/CHANGELOG.md).
